language: node_js
matrix:
  include:
    - node_js: "12"
cache:
  directories: [node_modules]
services:
  - postgresql
install:
  - npm ci
before_script:
  - psql -c 'create database til_test_db;' -U postgres
script:
  - cd rest-api && npm ci && npm run initdb && npm test
